use dbx_core::models::connection::{
    default_connect_timeout_secs, default_idle_timeout_secs, default_keepalive_interval_secs,
    default_query_timeout_secs, default_redis_key_separator, ConnectionConfig, DatabaseType,
};
use std::str::FromStr;

fn mysql_config(username: &str, password: &str, database: Option<&str>) -> ConnectionConfig {
    ConnectionConfig {
        oracle_oci_nls_lang: None,
        oracle_oci_tns_admin: None,
        docs_notes_path: None,
        id: "id".to_string(),
        name: "name".to_string(),
        note: String::new(),
        db_type: DatabaseType::Mysql,
        driver_profile: None,
        driver_label: None,
        url_params: None,
        agent_java_options: Vec::new(),
        host: "10.1.2.3".to_string(),
        port: 2883,
        username: username.to_string(),
        password: password.to_string(),
        database: database.map(str::to_string),
        default_schema: None,
        visible_databases: None,
        visible_database_patterns: None,
        visible_schemas: None,
        show_system_schemas: false,
        sidebar_auto_load_all_tables: false,
        attached_databases: Vec::new(),
        init_script: None,
        color: None,
        transport_layers: Vec::new(),
        connect_timeout_secs: default_connect_timeout_secs(),
        query_timeout_secs: default_query_timeout_secs(),
        idle_timeout_secs: default_idle_timeout_secs(),
        keepalive_interval_secs: default_keepalive_interval_secs(),
        ssl: false,
        ca_cert_path: String::new(),
        client_cert_path: String::new(),
        client_key_path: String::new(),
        sysdba: false,
        oracle_connection_type: None,
        connection_string: None,
        redis_connection_mode: None,
        redis_sentinel_master: String::new(),
        redis_sentinel_nodes: String::new(),
        redis_sentinel_username: String::new(),
        redis_sentinel_password: String::new(),
        redis_sentinel_tls: false,
        redis_cluster_nodes: String::new(),
        redis_key_separator: default_redis_key_separator(),
        redis_scan_page_size: None,
        redis_database_aliases: Default::default(),
        redis_key_templates: Vec::new(),
        redis_key_filter: None,
        redis_key_grouping: None,
        etcd_endpoints: String::new(),
        gbase_server: String::new(),
        informix_server: String::new(),
        external_config: None,
        plugin_id: None,
        plugin_connection_provider: None,
        plugin_connection_type: None,
        connection_secrets: Default::default(),
        jdbc_driver_class: None,
        jdbc_driver_paths: Vec::new(),
        one_time: false,
        save_password: true,
        read_only: false,
        is_production: false,
        production_databases: vec![],
        database_info: None,
    }
}
